{
  "openapi": "3.0.0",
  "info": {
    "title": "CoolWithCoule",
    "description": "api to interact with the CoolWithCoule online store.",
    "version": "0.1.9"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "Returns a list of products",
        "description": null,
        "parameters": [
          {
            "name": "id",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "upcCode",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "name",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "priceInCents",
            "in": "query",
            "required": false,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns a list of products",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "item": {
                    "$ref": "#/components/schemas/product"
                  },
                  "example": {
                    "products": [
                      {
                        "id": "fdsfd768fd76f76"
                      },
                      {
                        "name": "man with a pan"
                      },
                      {
                        "upcCode": "587-23457-534"
                      },
                      {
                        "description": "a man...with a pan...on an apron!"
                      },
                      {
                        "quantity": 27
                      },
                      {
                        "priceInCents": 19.99
                      },
                      {
                        "id": "fd987f68fsd78"
                      },
                      {
                        "name": "rosemary sage and f*** you"
                      },
                      {
                        "upcCode": "587-34562-534"
                      },
                      {
                        "description": "best restarant in town!"
                      },
                      {
                        "quantity": 23
                      },
                      {
                        "priceInCents": 19.99
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Creates a new product",
        "description": null,
        "parameters": [
          {
            "name": "callingUserId",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "upcCode",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "name",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "priceInCents",
            "in": "query",
            "required": true,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "description",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "quantity",
            "in": "query",
            "required": true,
            "schema": {
              "type": "number"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns a product",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "item": {
                    "$ref": "#/components/schemas/product"
                  },
                  "example": {
                    "id": "fdsfd768fd76f76",
                    "name": "man with a pan",
                    "upcCode": "587-23457-534",
                    "description": "a man...with a pan...on an apron!",
                    "quantity": 27,
                    "priceInCents": 19.99
                  }
                }
              }
            }
          }
        }
      }
    },
    "/products/{id}": {
      "get": {
        "summary": "returns a specific product by id",
        "description": null,
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns a product",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "item": {
                    "$ref": "#/components/schemas/product"
                  },
                  "example": {
                    "id": "fdsfd768fd76f76",
                    "name": "man with a pan",
                    "upcCode": "587-23457-534",
                    "description": "a man...with a pan...on an apron!",
                    "quantity": 27,
                    "priceInCents": 19.99
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "modifies the specified product",
        "description": null,
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "callingUserId",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "upcCode",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "quantity",
            "in": "query",
            "required": false,
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "description",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "priceInCents",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns a modified product",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "item": {
                    "$ref": "#/components/schemas/product"
                  },
                  "example": {
                    "id": "fdsfd768fd76f76",
                    "name": "man with a pan",
                    "upcCode": "587-23457-534",
                    "description": "a man...with a pan...on an apron!",
                    "quantity": 27,
                    "priceInCents": 19.99
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "removes a specific product by id",
        "description": null,
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "callingUserId",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns the removed product",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "item": {
                    "$ref": "#/components/schemas/product"
                  },
                  "example": {
                    "id": "fdsfd768fd76f76",
                    "name": "man with a pan",
                    "upcCode": "587-23457-534",
                    "description": "a man...with a pan...on an apron!",
                    "quantity": 27,
                    "priceInCents": 19.99
                  }
                }
              }
            }
          }
        }
      }
    },
    "/customers": {
      "post": {
        "summary": "Creates a user",
        "description": null,
        "parameters": [
          {
            "name": "email",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "password",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "name",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "callingUserId",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "isAdmin",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "a boolean true",
            "content": {
              "application/json": {
                "schema": {
                  "items": {
                    "type": "boolean"
                  },
                  "example": {
                    "success": true
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "summary": "Returns an user from provided email and password",
        "description": null,
        "parameters": [
          {
            "name": "email",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "password",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns a user",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "item": {
                    "$ref": "#/components/schemas/customer"
                  },
                  "example": {
                    "id": "fa7fg5343hjhs7as5",
                    "name": "John Doe",
                    "email": "balls2thewall@gmail.com",
                    "historyOrderIds": {
                      "id": [
                        "fjklsfjdlksadfjsa",
                        "fdjsakfldjsajkfds",
                        "fdskaslfjdalfj"
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/customers/{id}": {
      "get": {
        "summary": "gets a customer with provided id",
        "description": null,
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "callingUserId",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns a user",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "item": {
                    "$ref": "#/components/schemas/customer"
                  },
                  "example": {
                    "id": "fa7fg5343hjhs7as5",
                    "name": "John Doe",
                    "email": "balls2thewall@gmail.com",
                    "historyOrderIds": {
                      "id": [
                        "fjklsfjdlksadfjsa",
                        "fdjsakfldjsajkfds",
                        "fdskaslfjdalfj"
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "modifies a user from provided id",
        "description": null,
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "callingUserId",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns a user",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "item": {
                    "$ref": "#/components/schemas/customer"
                  },
                  "example": {
                    "id": "fa7fg5343hjhs7as5",
                    "name": "John Doe",
                    "email": "balls2thewall@gmail.com",
                    "historyOrderIds": {
                      "id": [
                        "fjklsfjdlksadfjsa",
                        "fdjsakfldjsajkfds",
                        "fdskaslfjdalfj"
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Removes a customer from the database",
        "description": null,
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "callingUserId",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "a boolean true",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "item": {
                    "$ref": "#/components/schemas/customer"
                  },
                  "example": {
                    "deleted": true
                  }
                }
              }
            }
          }
        }
      }
    },
    "/orders": {
      "get": {
        "summary": "returns a list of orders belonging to the customer",
        "description": null,
        "parameters": [
          {
            "name": "callingUserId",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "a list of orders",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "item": {
                    "$ref": "#/components/schemas/order"
                  },
                  "example": {
                    "id": "fjkhf87f6f5f6asf67",
                    "customer": {
                      "id": "fa7fg5343hjhs7as5",
                      "name": "John Doe",
                      "email": "balls2thewall@gmail.com",
                      "historyOrderIds": {
                        "id": [
                          "fjklsfjdlksadfjsa",
                          "fdjsakfldjsajkfds",
                          "fdskaslfjdalfj"
                        ]
                      }
                    },
                    "productIds": [
                      "fjklsfjdlksadfjsa",
                      "fdjsakfldjsajkfds",
                      "fdskaslfjdalfj"
                    ],
                    "orderDate": "Tue Oct 2 21:43:04Z 2019"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "creates a new order",
        "description": null,
        "parameters": [
          {
            "name": "customer",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "a list of orders",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "item": {
                    "$ref": "#/components/schemas/order"
                  },
                  "example": {
                    "id": "fjkhf87f6f5f6asf67",
                    "customer": {
                      "id": "fa7fg5343hjhs7as5",
                      "name": "John Doe",
                      "email": "balls2thewall@gmail.com",
                      "historyOrderIds": {
                        "id": [
                          "fjklsfjdlksadfjsa",
                          "fdjsakfldjsajkfds",
                          "fdskaslfjdalfj"
                        ]
                      }
                    },
                    "productIds": [
                      "fjklsfjdlksadfjsa",
                      "fdjsakfldjsajkfds",
                      "fdskaslfjdalfj"
                    ],
                    "orderDate": "Tue Oct 2 21:43:04Z 2019"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "error": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer"
          },
          "message": {
            "type": "string"
          }
        }
      },
      "customer": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "historyOrderIds": {
            "type": "array"
          }
        }
      },
      "product": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "upcCode": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "quantity": {
            "type": "number"
          },
          "priceInCents": {
            "type": "number"
          }
        }
      },
      "order": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "customer": {
            "type": "object"
          },
          "productIds": {
            "type": "array"
          },
          "orderDate": {
            "type": "string"
          }
        }
      }
    }
  }
}